### ISSUE TITLE
Quit Dialog does not terminate application

### ISSUE THREAD

**Issue by Ushpuppy** [josephdadams/screendeck#14]
The Quit dialog does not terminate the application

**To Reproduce**

1. Go to Tray Icon
2. Click on 'Quit"

**Expected behavior**
Expected to terminate process

**Comment by josephdadams** [comment]
Actively looking into this. See #11 

I will release a v1.0.1

**Comment by josephdadams** [comment]
fixed in https://github.com/josephdadams/screendeck/commit/a2eb04b7693b74b2c1ec93648a288e61a1a1a305
