### ISSUE TITLE
Starting another copy of application creates a new application process but does not produce additional window

### ISSUE THREAD

**Issue by Ushpuppy** [josephdadams/screendeck#15]
**Describe the bug**
Starting another copy of application creates a new application process but does not produce additional window

**To Reproduce**
1. Started 2nd version of application
2. Verified two versions running in tray
3. Attempted to bring up second window on separate page
4. Partial windows created "incomplete" unable to change settings

**Expected behavior**
Expected to be able to create a second window with separate settings be on another set of pages

**Comment by josephdadams** [comment]
The app is designed to only be running one at a time. See #7 I would like to add additional surface support in the future
