### ISSUE TITLE
Feature Request: auto reconnect

### ISSUE THREAD

**Issue by paule26** [josephdadams/screendeck#16]
When screendeck looses connection to the Companion-PC in the network, I have to close screendeck (in the moment kill it with the Taskmanager in Windows, but you knoe this issue) and restart it.
A auto-reconnect or at least a option to click on in screendeck to reconnect would be great

**Comment by josephdadams** [comment]
Oh great find! I’ll fix.

As a workaround, try opening Settings and not changing anything and clicking Save.

**Comment by paule26** [comment]
"As a workaround, try opening Settings and not changing anything and clicking Save"
No, it doesn't help, also changing parameters and rechange them doesn't help, you have to end the program

**Comment by davidjoshuaford** [comment]
Similar to this, I find it cumbersome to get the window back on screen once it's closed out without having to go through the settings again.

It would be great (faster) if clicking on the screendeck icon in the dock reopened the window, or using a shortcut such as Command-1 reopened the window. The Notes app on the Mac has similar behavior, where you can close all the windows down but still have the app running, and clicking on the icon, or using a shortcut will bring the main window back. 

Keep up the great work!

**Comment by josephdadams** [comment]
@davidjoshuaford do you have a "show keypad" in the tray menu? It should only appear when the window (the one with the streamdeck buttons) is closed

**Comment by josephdadams** [comment]
https://github.com/josephdadams/screendeck/commit/a93b9f2096e3e8b0011c89ca202ed6d90d741f0f

This commit adds some reconnect logic. Please open a new issue or we can re-open this one if issues persist. Download the latest version that I will be releasing shortly. Tagged as `v1.1.0`.

**Comment by paule26** [comment]
Auto reconnection works great, Thanks!
The only thing, after reconnection screendeck is no longer on top, it's behind e.g. PPT, closing and reopen helps

**Comment by josephdadams** [comment]
Would you mind opening a new issue about that?
