### ISSUE TITLE
After auto-reconnect not anymore on Top

### ISSUE THREAD

**Issue by paule26** [josephdadams/screendeck#21]
After automatic reconnection screendeck is no longer on top, it's behind e.g. PPT, closing and reopen helps

**Comment by josephdadams** [comment]
I have done some refinements, and the "show keypad" option helps bring it back to the top

**Comment by paule26** [comment]
The actual version 1.1.0 is without your changes, although they are listed, comes there a new release the next days or do I miss something?

**Comment by josephdadams** [comment]
`v1.2.0` is out now.
